
server:
  port: 8080

spring:
  application:
    name: erupt-quickstart
  datasource:
    url: jdbc:mysql://localhost:3306/erupt?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql